# Création d'un nouvel utilisateur qui va poster des messages
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "name": "user1",
  "surname": "user1",
  "username": "user1",
  "email": "user1.user1@example.com",
  "password": "123",
  "admin": true
}

###
# Connexion de l'utilisateur
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "12345"
}

###

# Pour créer un utilisateur avec les champs minimums
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "surname": "Taylor",
  "name": "Swift",
  "username": "taylorswift13",
  "email": "taylorswift@gmail.com",
  "password": "123456"
}

###
# Création d'un nouveau message
POST http://localhost:4000/posts/taylorswift13
Content-Type: application/json

{
  "message": "Eras tour in 2 days!",
  "privacy": false
}
###
# Nouveau message à partir de /
POST http://localhost:4000/posts/
Content-Type: application/json

{
  "author": "taylorswift13",
  "message": "Eras tour in 2 days! aekjjrakljrlka",
  "privacy": false
}

###
# Récupération de tous les posts 
GET http://localhost:4000/posts/


###
# Récupération de tous les posts d'un utilisateur
GET http://localhost:4000/posts/post/taylorswift13

###
# Récupération d'un post précis
GET http://localhost:4000/posts/663a47c86a079a47528f378a

###
# Récupération des posts privés
GET http://localhost:4000/posts/privatePosts

###
# Récupération des posts publics
GET http://localhost:4000/posts/publicPosts

###
# Suppression d'un post avec son id
DELETE http://localhost:4000/posts/delete/663a47c86a079a47528f378a
###
PATCH http://localhost:4000/posts/663a47c86a079a47528f378a
Content-Type: application/json

{
  "message": "The tortured poets department (the anthology) is out now !"
}

###
GET http://localhost:4000/posts/662d2d044017ee680474caa5

###

POST http://localhost:4000/posts/post/search/ 
Content-Type: application/json

{
  "keyword" : "Eras"
}
